package Vista;

import controlador.Propiedades;
import controlador.XmlActions;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import rojerusan.RSNotifyAnimated;

public class CAPTURA extends javax.swing.JFrame {

    int val = 0;
    Propiedades prop = new Propiedades();
    String ruta = "src/documentos/";
    String carpeta = "";
    boolean banderaEliminar = false;
    File periodo;
    XmlActions xml = new XmlActions();

    public CAPTURA() {
        initComponents();
        cleanIcons();
        this.setLocationRelativeTo(null);
        carpeta = prop.acceder("archivoActual", ruta + "config.properties");
        System.out.println(carpeta);
        periodo = new File(ruta + "Periodos/" + carpeta + "/Periodo.properties");
        System.out.println(periodo.getAbsolutePath());
        cargarCapturas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 248, 255));

        jPanel6.setBackground(new java.awt.Color(248, 248, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BtnMinDark.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(248, 248, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BtnXdark.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("CONTROL DE SERVICIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(258, 258, 258)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jPanel2.setBackground(new java.awt.Color(248, 248, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(248, 248, 255));
        jCheckBox1.setText("COORDINACION DE CARRERAS");
        jCheckBox1.setEnabled(false);
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(248, 248, 255));
        jCheckBox2.setText("CENTRO DE INFORMACION");
        jCheckBox2.setEnabled(false);
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(248, 248, 255));
        jCheckBox3.setText("DE COMPUTO");
        jCheckBox3.setEnabled(false);
        jPanel2.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(248, 248, 255));
        jCheckBox4.setText("RECURSOS FINANCIEROS");
        jCheckBox4.setEnabled(false);
        jPanel2.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jCheckBox8.setBackground(new java.awt.Color(248, 248, 255));
        jCheckBox8.setText("RESIDENCIAS PROFESIONALES");
        jCheckBox8.setEnabled(false);
        jPanel2.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jCheckBox9.setBackground(new java.awt.Color(248, 248, 255));
        jCheckBox9.setText("SERVICIOS ESCOLARES");
        jCheckBox9.setEnabled(false);
        jPanel2.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jCheckBox10.setBackground(new java.awt.Color(248, 248, 255));
        jCheckBox10.setText("SERVICIO SOCIAL");
        jCheckBox10.setEnabled(false);
        jPanel2.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel11.setText("ELIMINAR AVANCE");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listo.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listo.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listo.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listo.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listo.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listo.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listo.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jLabel19.setText("VOLVER AL MENU");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 53, 153));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("VER RESPUESTAS");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel20, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 260, 40));

        jPanel4.setBackground(new java.awt.Color(0, 53, 153));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("VER RESPUESTAS");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel21, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 260, 40));

        jPanel7.setBackground(new java.awt.Color(0, 53, 153));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("VER RESPUESTAS");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel22, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 260, 40));

        jPanel8.setBackground(new java.awt.Color(0, 53, 153));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("VER RESPUESTAS");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel23, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 260, 40));

        jPanel9.setBackground(new java.awt.Color(0, 53, 153));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("VER RESPUESTAS");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel24, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 260, 40));

        jPanel10.setBackground(new java.awt.Color(0, 53, 153));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("VER RESPUESTAS");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel25, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 260, 40));

        jPanel11.setBackground(new java.awt.Color(0, 53, 153));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("VER RESPUESTAS");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel26, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 260, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel27.setText("EDITAR SERVICIOS");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanIcons() {
        jLabel14.setVisible(false);
        jLabel13.setVisible(false);
        jLabel12.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        jPanel4.setVisible(false);
        jLabel21.setVisible(false);
        jPanel3.setVisible(false);
        jLabel20.setVisible(false);
        jPanel8.setVisible(false);
        jLabel23.setVisible(false);
        jPanel7.setVisible(false);
        jLabel22.setVisible(false);
        jPanel11.setVisible(false);
        jLabel26.setVisible(false);
        jPanel9.setVisible(false);
        jLabel24.setVisible(false);
        jPanel10.setVisible(false);
        jLabel25.setVisible(false);
    }

    private void cargarCapturas() {
        System.out.println("cargando capturas");
        boolean banderaReporte = true;
        String activo, iniciado, procesoTerminado;
        if (periodo.exists()) {
            activo = prop.acceder("centroInformacionActivo", periodo.getAbsolutePath());
            if (activo.equals("si")) {
                jCheckBox2.setSelected(true);
                iniciado = prop.acceder("centroDeInformacionExcel", periodo.getAbsolutePath());
                if (iniciado.equalsIgnoreCase("si")) {
                    jLabel2.setVisible(false);
                    jLabel29.setVisible(true);
                    jPanel4.setVisible(true);
                    jLabel21.setVisible(true);
                    jLabel37.setVisible(false);
                    procesoTerminado = prop.acceder("centroDeInformacionExcelTerminado", periodo.getAbsolutePath());
                    if (procesoTerminado.equals("si")) {
                        jLabel14.setVisible(true);
                    } else {
                        banderaReporte = false;

                    }
                } else {
                    jLabel2.setVisible(true);
                    jLabel29.setVisible(false);
                    jPanel4.setVisible(false);
                    jLabel21.setVisible(false);
                    jLabel37.setVisible(true);
                    banderaReporte = false;

                }
            } else {
                jLabel2.setVisible(false);
                jLabel29.setVisible(false);
                jLabel37.setVisible(false);
            }

            //
            activo = prop.acceder("coordinacionCarrerasActivo", periodo.getAbsolutePath());
            if (activo.equals("si")) {
                jCheckBox1.setSelected(true);
                iniciado = prop.acceder("coordinacionDeCarrerasExcel", periodo.getAbsolutePath());
                if (iniciado.equalsIgnoreCase("si")) {
                    jLabel1.setVisible(false);
                    jLabel28.setVisible(true);
                    jPanel3.setVisible(true);
                    jLabel20.setVisible(true);
                    jLabel36.setVisible(false);
                    procesoTerminado = prop.acceder("coordinacionDeCarrerasExcelTerminado", periodo.getAbsolutePath());
                    if (procesoTerminado.equals("si")) {
                        jLabel13.setVisible(true);
                    } else {
                        banderaReporte = false;
                    }
                } else {
                    jLabel1.setVisible(true);
                    jLabel28.setVisible(false);
                    jPanel3.setVisible(false);
                    jLabel20.setVisible(false);
                    jLabel36.setVisible(true);
                    banderaReporte = false;
                }
            } else {
                jLabel1.setVisible(false);
                jLabel28.setVisible(false);
                jLabel36.setVisible(false);
            }
            //
            activo = prop.acceder("recursosFinancierosActivo", periodo.getAbsolutePath());
            if (activo.equals("si")) {
                jCheckBox4.setSelected(true);
                iniciado = prop.acceder("recursosFinancierosExcel", periodo.getAbsolutePath());
                if (iniciado.equalsIgnoreCase("si")) {
                    jLabel6.setVisible(false);
                    jLabel31.setVisible(true);
                    jPanel8.setVisible(true);
                    jLabel23.setVisible(true);
                    jLabel35.setVisible(false);
                    procesoTerminado = prop.acceder("recursosFinancierosExcelTerminado", periodo.getAbsolutePath());
                    if (procesoTerminado.equals("si")) {
                        jLabel12.setVisible(true);
                    } else {
                        banderaReporte = false;
                    }
                } else {
                    jLabel6.setVisible(true);
                    jLabel31.setVisible(false);
                    jPanel8.setVisible(false);
                    jLabel23.setVisible(false);
                    jLabel35.setVisible(true);
                    banderaReporte = false;
                }
            } else {
                jLabel6.setVisible(false);
                jLabel31.setVisible(false);
                jLabel35.setVisible(false);
            }
            //
            activo = prop.acceder("computoActivo", periodo.getAbsolutePath());
            if (activo.equals("si")) {
                jCheckBox3.setSelected(true);
                iniciado = prop.acceder("computoExcel", periodo.getAbsolutePath());
                if (iniciado.equalsIgnoreCase("si")) {
                    jLabel3.setVisible(false);
                    jLabel30.setVisible(true);
                    jPanel7.setVisible(true);
                    jLabel22.setVisible(true);
                    jLabel38.setVisible(false);
                    procesoTerminado = prop.acceder("computoExcelTerminado", periodo.getAbsolutePath());
                    if (procesoTerminado.equals("si")) {
                        jLabel15.setVisible(true);
                    } else {
                        banderaReporte = false;
                    }
                } else {
                    jLabel3.setVisible(true);
                    jLabel30.setVisible(false);
                    jPanel7.setVisible(false);
                    jLabel22.setVisible(false);
                    jLabel38.setVisible(true);
                    banderaReporte = false;
                }
            } else {
                jLabel3.setVisible(false);
                jLabel30.setVisible(false);
                jLabel38.setVisible(false);
            }
            //
            activo = prop.acceder("servicioSocialActivo", periodo.getAbsolutePath());
            if (activo.equals("si")) {
                jCheckBox10.setSelected(true);
                iniciado = prop.acceder("servicioSocialExcel", periodo.getAbsolutePath());
                if (iniciado.equalsIgnoreCase("si")) {
                    jLabel10.setVisible(false);
                    jLabel33.setVisible(true);
                    jPanel11.setVisible(true);
                    jLabel26.setVisible(true);
                    jLabel39.setVisible(false);
                    procesoTerminado = prop.acceder("servicioSocialExcelTerminado", periodo.getAbsolutePath());
                    if (procesoTerminado.equals("si")) {
                        jLabel16.setVisible(true);
                    } else {
                        banderaReporte = false;
                    }
                } else {
                    jLabel10.setVisible(true);
                    jLabel33.setVisible(false);
                    jPanel11.setVisible(false);
                    jLabel26.setVisible(false);
                    jLabel39.setVisible(true);
                    banderaReporte = false;
                }
            } else {
                jLabel10.setVisible(false);
                jLabel33.setVisible(false);
                jLabel39.setVisible(false);
            }
            //
            activo = prop.acceder("serviciosEscolaresActivo", periodo.getAbsolutePath());
            if (activo.equals("si")) {
                jCheckBox9.setSelected(true);
                iniciado = prop.acceder("serviciosEscolaresExcel", periodo.getAbsolutePath());
                if (iniciado.equalsIgnoreCase("si")) {
                    jLabel9.setVisible(false);
                    jLabel34.setVisible(true);
                    jPanel9.setVisible(true);
                    jLabel24.setVisible(true);
                    jLabel41.setVisible(false);
                    procesoTerminado = prop.acceder("serviciosEscolaresExcelTerminado", periodo.getAbsolutePath());
                    if (procesoTerminado.equals("si")) {
                        jLabel18.setVisible(true);
                    } else {
                        banderaReporte = false;
                    }
                } else {
                    jLabel9.setVisible(true);
                    jLabel34.setVisible(false);
                    jPanel9.setVisible(false);
                    jLabel24.setVisible(false);
                    jLabel41.setVisible(true);
                    banderaReporte = false;
                }
            } else {
                jLabel9.setVisible(false);
                jLabel34.setVisible(false);
                jLabel41.setVisible(false);
            }
            //
            activo = prop.acceder("residenciaProfesionalActivo", periodo.getAbsolutePath());
            if (activo.equals("si")) {
                jCheckBox8.setSelected(true);
                iniciado = prop.acceder("residenciasProfesionalesExcel", periodo.getAbsolutePath());
                if (iniciado.equalsIgnoreCase("si")) {
                    jLabel8.setVisible(false);
                    jLabel32.setVisible(true);
                    jPanel10.setVisible(true);
                    jLabel25.setVisible(true);
                    jLabel40.setVisible(false);
                    procesoTerminado = prop.acceder("residenciasProfesionalesExcelTerminado", periodo.getAbsolutePath());
                    if (procesoTerminado.equals("si")) {
                        jLabel17.setVisible(true);
                    } else {
                        banderaReporte = false;
                    }
                } else {
                    jLabel8.setVisible(true);
                    jLabel32.setVisible(false);
                    jPanel10.setVisible(false);
                    jLabel25.setVisible(false);
                    jLabel40.setVisible(true);
                    banderaReporte = false;
                }
            } else {
                jLabel8.setVisible(false);
                jLabel32.setVisible(false);
                jLabel40.setVisible(false);
            }
            //
            if (banderaReporte) {
                //btnReporte.setDisable(false);
                //btnFinalizar.setDisable(false);
            }
            procesoFinal();
        } else {
            System.out.println("error");
        }
    }

    private void procesoFinal() {

    }
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jPanel6.setBackground(Color.red);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(248, 248, 255));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jPanel5.setBackground(Color.red);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(248, 248, 255));
    }//GEN-LAST:event_jLabel4MouseExited
    private boolean deleteExcel(String name) {
        File file = new File(ruta + "Periodos/" + carpeta + "/" + name);
        System.out.println(ruta + "Periodos/" + carpeta + "/" + name);
        if (file.delete()) {
            JOptionPane.showMessageDialog(null, "Eliminando, por favor espere...");
            try {
                Thread.sleep(3000);
            } catch (Exception e) {
            }
            new rojerusan.RSNotifyAnimated("Listo!", "El archivo fue eliminado con exito.", 4,
                    RSNotifyAnimated.PositionNotify.BottomRight,
                    RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
            return true;
        } else {
            new rojerusan.RSNotifyAnimated("ERROR!", "El archivo no se pudo eliminar del sistema.", 4,
                    RSNotifyAnimated.PositionNotify.BottomRight,
                    RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            return false;
        }
    }

    private boolean cargarExcel(String name) {
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel", "xlsx", "csv");
        jf.setFileFilter(filter);
        jf.setDialogTitle("Seleccione el archivo excel de la encuesta");
        int result = jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        if (archivo != null) {
            if (result != JFileChooser.CANCEL_OPTION) {
                try {
                    String Dest2 = System.getProperty("user.dir") + "/src/Documentos/Periodos/" + carpeta + "/" + name;
                    System.out.println(Dest2);
                    Path Destino = Paths.get(Dest2);

                    String orig = archivo.getPath();
                    Path origen = Paths.get(orig);

                    Files.copy(origen, Destino, REPLACE_EXISTING);
                    new rojerusan.RSNotifyAnimated("Listo!", "El archivo fue añadido con exito.", 4,
                            RSNotifyAnimated.PositionNotify.BottomRight,
                            RSNotifyAnimated.AnimationNotify.BottomUp,
                            RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                    return true;
                } catch (IOException e) {
                    new rojerusan.RSNotifyAnimated("ERROR!", "El archivo no se pudo agregar al sistema.", 4,
                            RSNotifyAnimated.PositionNotify.BottomRight,
                            RSNotifyAnimated.AnimationNotify.BottomUp,
                            RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
                    System.out.println(e);
                    return false;
                }
            }
        }
        return false;
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (cargarExcel("centroDeInformacionExcel.xlsx")) {
            prop.guardar("centroDeInformacionExcel", "si", periodo.getAbsolutePath());
            cargarCapturas();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (cargarExcel("coordinacionDeCarrerasExcel.xlsx")) {
            prop.guardar("coordinacionDeCarrerasExcel", "si", periodo.getAbsolutePath());
            cargarCapturas();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if (cargarExcel("recursosFinancierosExcel.xlsx")) {
            prop.guardar("recursosFinancierosExcel", "si", periodo.getAbsolutePath());
            cargarCapturas();
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (cargarExcel("computoExcel.xlsx")) {
            prop.guardar("computoExcel", "si", periodo.getAbsolutePath());
            cargarCapturas();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        if (cargarExcel("servicioSocialExcel.xlsx")) {
            prop.guardar("servicioSocialExcel", "si", periodo.getAbsolutePath());
            cargarCapturas();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (cargarExcel("serviciosEscolaresExcel.xlsx")) {
            prop.guardar("serviciosEscolaresExcel", "si", periodo.getAbsolutePath());
            cargarCapturas();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        if (cargarExcel("residenciasProfesionalesExcel.xlsx")) {
            prop.guardar("residenciasProfesionalesExcel", "si", periodo.getAbsolutePath());
            cargarCapturas();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void showAnswers(String excel, String title, String clave) {
        String path = "src/Documentos/Periodos/" + carpeta;
        File localizacion = new File(path);
        String p = localizacion.getAbsolutePath() + "\\" + excel;
        System.out.println(p);
        verRespuestas obj = new verRespuestas(p, title, clave);
        obj.setVisible(true);
        this.dispose();
    }
    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        //centro de informacion
        showAnswers("centroDeInformacionExcel.xlsx", "CENTRO DE INFORMACION", "Centro");
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        //coordinacion de carreras
        showAnswers("coordinacionDeCarrerasExcel.xlsx", "COORDINACION DE CARRERAS","Coordinacion");
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        //recursos financieros
        showAnswers("recursosFinancierosExcel.xlsx", "RECURSOS FINANCIEROS","Financieros");
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // de computo
        showAnswers("computoExcel.xlsx", "DE COMPUTO","Computo");
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        //servicio social
        showAnswers("servicioSocialExcel.xlsx", "SERVICIO SOCIAL","Social");
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // servicios escolares
        showAnswers("serviciosEscolaresExcel.xlsx", "SERVICIOS ESCOLARES","Escolares");
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // residencia
        showAnswers("residenciasProfesionalesExcel.xlsx", "RESIDENCIAS PROFESIONALES","Residencias");
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        MENU obj = new MENU();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        OpcServicio obj = new OpcServicio();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el excel de Centro de Informacion?", "Archivos Excel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            if (deleteExcel("centroDeInformacionExcel.xlsx")) {
                if (prop.guardar("centroDeInformacionExcel", "no", periodo.getAbsolutePath())) {
                    System.out.println("actualizado");
                    cargarCapturas();
                }
            }
        }

    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el excel de Coordinacion de Carreras?", "Archivos Excel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            if (deleteExcel("coordinacionDeCarrerasExcel.xlsx")) {
                if (prop.guardar("coordinacionDeCarrerasExcel", "no", periodo.getAbsolutePath())) {
                    System.out.println("actualizado");
                    cargarCapturas();
                }
            }
        }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el excel de Recursos Financieros?", "Archivos Excel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            if (deleteExcel("recursosFinancierosExcel.xlsx")) {
                if (prop.guardar("recursosFinancierosExcel", "no", periodo.getAbsolutePath())) {
                    System.out.println("actualizado");
                    cargarCapturas();
                }
            }
        }
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el excel de Centro de Computo?", "Archivos Excel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            if (deleteExcel("computoExcel.xlsx")) {
                if (prop.guardar("computoExcel", "no", periodo.getAbsolutePath())) {
                    System.out.println("actualizado");
                    cargarCapturas();
                }
            }
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el excel de Servicio Social?", "Archivos Excel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            if (deleteExcel("servicioSocialExcel.xlsx")) {
                if (prop.guardar("servicioSocialExcel", "no", periodo.getAbsolutePath())) {
                    System.out.println("actualizado");
                    cargarCapturas();
                }
            }
        }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el excel de Servicios Escolares?", "Archivos Excel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            if (deleteExcel("serviciosEscolaresExcel.xlsx")) {
                if (prop.guardar("serviciosEscolaresExcel", "no", periodo.getAbsolutePath())) {
                    System.out.println("actualizado");
                    cargarCapturas();
                }
            }
        }
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el excel de Residencia Profesional?", "Archivos Excel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            if (deleteExcel("residenciasProfesionalesExcel.xlsx")) {
                if (prop.guardar("residenciasProfesionalesExcel", "no", periodo.getAbsolutePath())) {
                    System.out.println("actualizado");
                    cargarCapturas();
                }
            }
        }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void editPreguntas(String area){
        opcPregunta obj = new opcPregunta(area);
        obj.setVisible(true);
        this.dispose();
    }
    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
        editPreguntas("Centro");
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        editPreguntas("Coordinacion");
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        editPreguntas("Financieros");
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        editPreguntas("Computo");
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        editPreguntas("Social");
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
        editPreguntas("Escolares");
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        editPreguntas("Residencias");
    }//GEN-LAST:event_jLabel40MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAPTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAPTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAPTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAPTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAPTURA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
