/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Carrera;
import controlador.Propiedades;
import controlador.XmlActions;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Yael_
 */
public class OpcMuestra extends javax.swing.JFrame {

    /**
     * Creates new form OpcMuestra
     */
    //muestra
    double n;  //resultado n
    double Encuestas;  //resultado n
    double Z = 1.96; //z -->95%
    double p = .5;
    double q = .5;
    double e = .05; //error -->5%
    int Nservicios = 7;
    //archivo muestra
    Propiedades prop = new Propiedades();
    String ruta = "src/Documentos/muestra.properties";
    //globales
    boolean flag = false;
    List<Carrera> carreras = new ArrayList();
    int tam = 0;
    XmlActions xml = new XmlActions();

    public OpcMuestra() {
        initComponents();
        this.setLocationRelativeTo(null);
        setEmptyInterface();
        carreras = xml.loadCarrerasDataFromFile(new File("src/Documentos/carreras.xml"));
        tam = carreras.size();
        llenarCarreras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 248, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 53, 153));
        jLabel1.setText("GENERACION DE MUESTRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 53, 153));
        jLabel2.setText("SELECCIONA LA CARRERA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 53, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carreras del ITZ" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 319, 38));

        jButton1.setText("CARGAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel3.setText("LA MUESTRA PARA LA CARRERA SELECCIONADA ES:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel4.setText("NUMERO DE ENCUESTAS POR SERVICIO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 260, 30));

        jLabel5.setText("TOTAL DE ALUMNOS DE LA CARRERA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 220, 210, -1));

        jTextField2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 270, 210, -1));

        jTextField3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 210, -1));

        jButton2.setText("EDITAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 230, 50));

        jButton4.setText("guardar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String aux = jComboBox1.getSelectedItem().toString();
        if (!aux.equalsIgnoreCase("Carreras del ITZ")) {
            showInterface();
            jTextField1.setText(prop.acceder("alumnos"+jComboBox1.getSelectedItem().toString().trim(), ruta));
            jTextField2.setText(prop.acceder("base"+jComboBox1.getSelectedItem().toString().trim(), ruta));
            jTextField3.setText(prop.acceder("muestra"+jComboBox1.getSelectedItem().toString().trim(), ruta));
        } else {
            JOptionPane.showMessageDialog(null, "Aun no has seleccionado una carrera");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        flag = true;
        jTextField1.setEnabled(true);
        jTextField2.setText("");
        jTextField3.setText("");

    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        // TODO add your handling code here:
        try {
            setMuestra(Integer.parseInt(jTextField1.getText()));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if (!jTextField1.getText().matches("[0-9--]*")) {
            JOptionPane.showMessageDialog(null, "Solo se admiten numeros");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        MUESTRA obj = new MUESTRA();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if (flag && !jTextField1.getText().toString().equalsIgnoreCase("")) {
            if (!jTextField2.getText().toString().equalsIgnoreCase("")
                    && !jTextField3.getText().toString().equalsIgnoreCase("")
                    && !jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Carreras del ITZ")) {
                int resp = JOptionPane.showConfirmDialog(null, "¿Deseas guardar los cambios?", "Ajustes Generales del Documento", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (resp == 0) {
                    boolean mensaje = false;
                    mensaje = prop.guardar("alumnos"+jComboBox1.getSelectedItem().toString().trim(), jTextField1.getText().trim(), ruta);
                    mensaje = prop.guardar("base"+jComboBox1.getSelectedItem().toString().trim(), jTextField2.getText().trim(), ruta);
                    mensaje = prop.guardar("muestra"+jComboBox1.getSelectedItem().toString().trim(), jTextField3.getText().trim(), ruta);
                    if (mensaje) {
                        JOptionPane.showMessageDialog(null, "Se ha guardado con exito!.", "Generacion de Muestra.", JOptionPane.INFORMATION_MESSAGE);
                        flag=false;
                        setEmptyInterface();
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR: No se han guardado los cambios.", "Generacion de Muestra.", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se han guardado los cambios.", "Generacion de Muestra.", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algun campo esta vacio.", "ERROR!", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No puedes dejar el total de alumnos en blanco.");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    private void setMuestra(int N) {
        n = (Math.pow(Z, 2) * p * q * N) / (Math.pow(e, 2) * (N - 1) + Math.pow(Z, 2) * p * q);
        n = Math.round(n);
        Encuestas = Math.round(n) / Nservicios;
        jTextField2.setText(String.valueOf(n));
        jTextField3.setText(String.valueOf(Encuestas));
    }

    private void setEmptyInterface() {
        jLabel5.setVisible(false);
        jTextField1.setVisible(false);
        jButton2.setVisible(false);
        jLabel3.setVisible(false);
        jTextField2.setVisible(false);
        jLabel4.setVisible(false);
        jTextField3.setVisible(false);
    }

    private void showInterface() {
        jLabel5.setVisible(true);
        jTextField1.setVisible(true);
        jTextField1.setEnabled(false);
        jButton2.setVisible(true);
        jLabel3.setVisible(true);
        jTextField2.setVisible(true);
        jTextField2.setEnabled(false);
        jLabel4.setVisible(true);
        jTextField3.setVisible(true);
        jTextField3.setEnabled(false);
    }

    private void llenarCarreras() {
        jComboBox1.removeAll();
        for (int i = 0; i < tam; i++) {
            String aux = carreras.get(i).getNombre();
            jComboBox1.addItem(aux);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcMuestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcMuestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
